export { default as DSANavBar } from "./navbar";
export { default as DSAText } from "./text";
export { default as DSAButton } from "./button";
export { default as DSAIconSocial } from "./iconSocial";
export { default as DSAResponsiveNavbar } from "./responsiveNavbar";
// export { default as DSAIconCloud } from "./iconCloud";
export { default as DSANavPortfolio } from "./navPortfolio";
export { default as DSACardProject } from "./cardProject";
export { default as DSACardCertificate } from "./cardCertificate";
export { default as DSACardSkill } from "./cardSkill";
export { default as DSAContactMeMessage } from "./contactMeMessage";
export { default as DSAInputForm } from "./inputForm";
export { default as DSATextArea } from "./textArea";
export { default as DSASocialLink } from "./socialLink";
export { default as DSACardSocialLinks } from "./cardSocialLinks";